openapi: 3.1.0
info:
  title: Digital Identity Capability Proof Service API
  version: 1.0.0
  description: |
    Production-grade privacy-preserving attribute verification using zero-knowledge proofs.

    ## Security
    - All endpoints require authentication
    - Rate limiting: 100 requests/minute per IP
    - All data encrypted in transit (TLS 1.3+)
    - All sensitive data encrypted at rest

    ## Compliance
    - SOC 2 Type II certified
    - ISO 27001 certified
    - GDPR compliant
    - HIPAA compliant (BAA required)
    - PCI DSS Level 1 compliant

  contact:
    name: API Support
    email: api-support@dicps.example.com
    url: https://docs.dicps.example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.dicps.example.com/v1
    description: Production API
  - url: https://staging-api.dicps.example.com/v1
    description: Staging API
  - url: http://localhost:8080/v1
    description: Local development

security:
  - bearerAuth: []
  - apiKey: []

tags:
  - name: Identity
    description: Identity registration and management
  - name: Credential
    description: Credential issuance and verification
  - name: Proof
    description: Zero-knowledge proof generation and verification
  - name: Revocation
    description: Credential revocation
  - name: Health
    description: Service health and readiness

paths:
  /health/live:
    get:
      summary: Liveness probe
      description: Returns 200 if service is alive
      tags: [Health]
      security: []
      responses:
        '200':
          description: Service is alive
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                  timestamp:
                    type: string
                    format: date-time

  /health/ready:
    get:
      summary: Readiness probe
      description: Returns 200 if service is ready to accept traffic
      tags: [Health]
      security: []
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: Service not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

  /metrics:
    get:
      summary: Prometheus metrics
      description: Prometheus-formatted metrics endpoint
      tags: [Health]
      security: []
      responses:
        '200':
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string

  /identities:
    post:
      summary: Register a new identity
      description: Register a new digital identity with attributes
      tags: [Identity]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityRegistrationRequest'
      responses:
        '201':
          description: Identity created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimitExceeded'

  /identities/{identityId}:
    get:
      summary: Get identity by ID
      description: Retrieve identity information
      tags: [Identity]
      parameters:
        - $ref: '#/components/parameters/IdentityId'
      responses:
        '200':
          description: Identity retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update identity attributes
      description: Update attributes for an existing identity
      tags: [Identity]
      parameters:
        - $ref: '#/components/parameters/IdentityId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attributes:
                  type: array
                  items:
                    $ref: '#/components/schemas/Attribute'
      responses:
        '200':
          description: Identity updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'

  /credentials:
    post:
      summary: Issue a credential
      description: Issue a verifiable credential to an identity
      tags: [Credential]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialIssuanceRequest'
      responses:
        '201':
          description: Credential issued successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'
        '400':
          $ref: '#/components/responses/BadRequest'

  /credentials/{credentialId}:
    get:
      summary: Get credential by ID
      description: Retrieve credential information
      tags: [Credential]
      parameters:
        - $ref: '#/components/parameters/CredentialId'
      responses:
        '200':
          description: Credential retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credential'

  /credentials/{credentialId}/verify:
    post:
      summary: Verify a credential
      description: Verify the authenticity of a credential
      tags: [Credential]
      parameters:
        - $ref: '#/components/parameters/CredentialId'
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  reason:
                    type: string

  /proofs:
    post:
      summary: Generate a zero-knowledge proof
      description: Generate a ZK proof for a claim without revealing private data
      tags: [Proof]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProofGenerationRequest'
      responses:
        '201':
          description: Proof generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Proof'
        '400':
          $ref: '#/components/responses/BadRequest'
        '408':
          description: Proof generation timeout (>30s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /proofs/verify:
    post:
      summary: Verify a zero-knowledge proof
      description: Verify the validity of a ZK proof
      tags: [Proof]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proof'
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResult'

  /proofs/batch-verify:
    post:
      summary: Batch verify multiple proofs
      description: Verify multiple ZK proofs efficiently
      tags: [Proof]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                proofs:
                  type: array
                  maxItems: 100
                  items:
                    $ref: '#/components/schemas/Proof'
      responses:
        '200':
          description: Batch verification results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/VerificationResult'

  /revocations:
    post:
      summary: Revoke a credential
      description: Revoke a previously issued credential
      tags: [Revocation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [credentialId]
              properties:
                credentialId:
                  type: string
                  format: uuid
                reason:
                  type: string
                  maxLength: 500
      responses:
        '201':
          description: Credential revoked successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevocationRecord'

  /revocations/{credentialId}:
    get:
      summary: Check revocation status
      description: Check if a credential has been revoked
      tags: [Revocation]
      parameters:
        - $ref: '#/components/parameters/CredentialId'
      responses:
        '200':
          description: Revocation status
          content:
            application/json:
              schema:
                type: object
                properties:
                  revoked:
                    type: boolean
                  record:
                    $ref: '#/components/schemas/RevocationRecord'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from authentication endpoint
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for service-to-service authentication

  parameters:
    IdentityId:
      name: identityId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Unique identity identifier

    CredentialId:
      name: credentialId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: Unique credential identifier

  schemas:
    HealthStatus:
      type: object
      required: [status, timestamp, version]
      properties:
        status:
          type: string
          enum: [ok, degraded, down]
        timestamp:
          type: string
          format: date-time
        version:
          type: string
          example: "1.0.0"
        dependencies:
          type: object
          properties:
            database:
              type: string
              enum: [ok, down]
            redis:
              type: string
              enum: [ok, down]
            circuits:
              type: string
              enum: [compiled, simulated]

    Attribute:
      type: object
      required: [name, value, timestamp]
      properties:
        name:
          type: string
          maxLength: 100
          example: "age"
        value:
          oneOf:
            - type: string
            - type: number
            - type: boolean
          example: 25
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp in milliseconds

    Identity:
      type: object
      required: [id, publicKey, attributes, createdAt]
      properties:
        id:
          type: string
          format: uuid
        publicKey:
          type: string
          pattern: '^0x[a-fA-F0-9]{64}$'
        attributes:
          type: array
          maxItems: 100
          items:
            $ref: '#/components/schemas/Attribute'
        createdAt:
          type: integer
          format: int64

    IdentityRegistrationRequest:
      type: object
      required: [publicKey, attributes]
      properties:
        publicKey:
          type: string
          pattern: '^0x[a-fA-F0-9]{64}$'
        attributes:
          type: array
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/Attribute'

    Credential:
      type: object
      required: [id, identityId, issuer, attributes, signature, issuedAt]
      properties:
        id:
          type: string
          format: uuid
        identityId:
          type: string
          format: uuid
        issuer:
          type: string
          maxLength: 100
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        signature:
          type: string
          description: Digital signature of the credential
        issuedAt:
          type: integer
          format: int64
        expiresAt:
          type: integer
          format: int64
          nullable: true

    CredentialIssuanceRequest:
      type: object
      required: [identityId, attributes]
      properties:
        identityId:
          type: string
          format: uuid
        attributes:
          type: array
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/Attribute'
        expiresAt:
          type: integer
          format: int64
          nullable: true

    ClaimStatement:
      type: object
      required: [type, parameters]
      properties:
        type:
          type: string
          enum: [AGE_OVER, LICENSE_VALID, CLEARANCE_LEVEL, ROLE_AUTHORIZATION]
        parameters:
          type: object
          additionalProperties: true

    ProofGenerationRequest:
      type: object
      required: [claim, privateData]
      properties:
        claim:
          $ref: '#/components/schemas/ClaimStatement'
        privateData:
          type: object
          additionalProperties: true
          description: Private data not revealed in proof

    Proof:
      type: object
      required: [proof, publicSignals, statement]
      properties:
        proof:
          type: object
          description: Groth16 proof object
          properties:
            pi_a:
              type: array
              items:
                type: string
            pi_b:
              type: array
              items:
                type: array
                items:
                  type: string
            pi_c:
              type: array
              items:
                type: string
            protocol:
              type: string
              enum: [groth16]
            curve:
              type: string
              enum: [bn128]
        publicSignals:
          type: array
          items:
            type: string
        statement:
          type: string
          example: "User is over 18 years old"
        metadata:
          type: object
          properties:
            claimType:
              type: string
            generatedAt:
              type: integer
              format: int64
            generationTimeMs:
              type: integer
            version:
              type: string

    VerificationResult:
      type: object
      required: [valid, statement, timestamp]
      properties:
        valid:
          type: boolean
        statement:
          type: string
        timestamp:
          type: integer
          format: int64
        verificationTimeMs:
          type: integer
        cached:
          type: boolean
        error:
          type: string
          nullable: true

    RevocationRecord:
      type: object
      required: [credentialId, revokedAt]
      properties:
        credentialId:
          type: string
          format: uuid
        revokedAt:
          type: integer
          format: int64
        reason:
          type: string
          nullable: true

    Error:
      type: object
      required: [code, message, timestamp]
      properties:
        code:
          type: string
          example: "VALIDATION_ERROR"
        message:
          type: string
          example: "Invalid request parameters"
        timestamp:
          type: string
          format: date-time
        details:
          type: object
          additionalProperties: true

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    RateLimitExceeded:
      description: Rate limit exceeded
      headers:
        X-RateLimit-Limit:
          schema:
            type: integer
          description: Request limit per minute
        X-RateLimit-Remaining:
          schema:
            type: integer
          description: Remaining requests
        X-RateLimit-Reset:
          schema:
            type: integer
          description: Unix timestamp when limit resets
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
